### ISSUE TITLE
Create a wiki page for the working groups

### ISSUE THREAD

**Issue by ensowhat** [mozilla-b2g/B2GOS-community#1]
- [x] Create a page on the wiki

https://wiki.mozilla.org/index.php?title=B2G/Transition_Project/Working_Groups
- [x] Add the link on discourse
- [x] at least 1 person added contact information on the wiki page for each working groups

In order to have at least one "reference person" to contact

**Comment by lapineige** [comment]
Wiki page created: https://wiki.mozilla.org/B2G/Transition_Project/Working_Groups
Please help to fill it :)

**Comment by lapineige** [comment]
Link added on discourse https://discourse.mozilla-community.org/t/b2g-working-groups-list-on-the-wiki/8888

**Comment by lapineige** [comment]
- [ ] People added their contact information on the wiki page

**Comment by kskarthik** [comment]
check the 3rd box too :) it's done

**Comment by lapineige** [comment]
Done :)
(but well, it was closed ^^)
