### ISSUE TITLE
Merge working group meetings into the weekly meeting

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#12]
In order to keep things short and easy to follow.
- [x] Update agenda (https://calendar.google.com/calendar/embed?src=bW96aWxsYS5jb21fMmQzNjM4MzUzMTM3MzQzMzMzMzczMzMyQHJlc291cmNlLmNhbGVuZGFyLmdvb2dsZS5jb20&rm=minimal)
- [x] Remind people on discourse / telegram / dev-fxos / IRC
- [ ] Current time seem to be blocking for some people, we should ask to know if they would prefer to change

**Comment by lapineige** [comment]
@ensowhat can you please update the agenda ?
I call help spreading the information on the different channels

**Comment by lapineige** [comment]
Should we ask people to know what day/time they prefer, to place the meeting according to contributors constraints ?
Should we change the time on a regular basis, to fit better with timezone ?

**Comment by lapineige** [comment]
Decision of today meeting:
- [ ] ask people on discourse if current time is a problem

If no,  close this task :)
- [ ] If yes, discuss about solution during next meeting

I will do that.

**Comment by lapineige** [comment]
- [x] @ensowhat updated the agenda

**Comment by lapineige** [comment]
- [x] Update on telegram done, the same on discourse.
- [ ] Need to be done on IRC / mailing-list (well, is it needed as it is on discourse ?)

Meeting time still seem to be a problem for quite a lot of people.

**Comment by Ryuno-Ki** [comment]
I'd suggest to ask, who is generally interested in participating. Those should provide their timezone.

Say, we have few Europeans, then a time could be determined, which suits USA and Asia best.

Another idea: Rotate the time with respect to a fixed rhythm. (For example, every second week at X o'clock and Y o'clock for all other ones for a weekly meeting).

Can the reminder me automated? Which IRC channel/mailing list especially?

**Comment by lapineige** [comment]
@Ryuno-Ki yes but thinking about the solution need to be done after being sure that we identify the issue (is it really a matter of meeting time ?)
As decided during a previous weekly meeting, we first need to ask people if the current meeting time is fine for them.
Can someone ask the question on discourse ? I don't have time to do it.

**Comment by lapineige** [comment]
The discussion about the meeting time is also located on discourse / meetings discussions - with no decision yet.
The main task is done, I close this issue.
