### ISSUE TITLE
Create a Get started page on MDN for new developers

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#16]
The goal is to have a really clear get started page for new-coming developers, that help them to be able to get B2G code, patch and build it, and submit the patch in a reasonably short time.
- [ ] Create a Get started page on MDN for new developers
  Cf. https://docs.google.com/presentation/d/1YuQaLr-hiduT5xyT4TaiaUDYOsZAnmadduevAE6MOKo/edit?usp=sharing
- [ ] Explain how to make a patch
- [ ] Add links to building instructions (for testing)
- [ ] Add links to debugging instructions (for testing)
- [ ] Explain how to submit a patch
- [ ] Add link to mentoring sessions documents
- [ ] Ask for review with experienced developers (o validate the content) and newcomers/recent contributor (for the clarity)

**Comment by ensowhat** [comment]
Cf. https://docs.google.com/presentation/d/1YuQaLr-hiduT5xyT4TaiaUDYOsZAnmadduevAE6MOKo/edit?usp=sharing as a starting point.
