### ISSUE TITLE
Update wiki after the end of the transition period

### ISSUE THREAD

**Issue by ensowhat** [mozilla-b2g/B2GOS-community#17]
Mainly on https://wiki.mozilla.org/B2G/Transition_Project

**Comment by lapineige** [comment]
Decided today during documentation meeting: https://wiki.mozilla.org/B2G/ should be the main page, with presentation of the project, and listing every useful link and categories.
https://wiki.mozilla.org/B2G/Transition_Project will be linked to this page, and adapted to be here as an history of the transition phase.

I've setup a milestone for that: https://github.com/mozilla-b2g/B2GOS-community/milestones/Adapt%20the%20documentation%20to%20the%20new%20phase
The goal is to do it before next meeting.

**Comment by lapineige** [comment]
@ensowhat @kskarthik would you like to help me on this point ?

**Comment by lapineige** [comment]
Need to add link to the "technical main page" on MDN #18

**Comment by lapineige** [comment]
Can be done on Thursday #19
