### ISSUE TITLE
Update MDN after the end of the transition period

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#18]
Decided today during documentation meeting: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS is the main page for developers / technical contributors (but as to be link to the wiki main page, see #17 - a link in the other way is also useful).

The actual page is fine, but we need to adapt it to the new status: we are no longer on transition phase. Some content need to be updated, while keeping link to transition project description (on the wiki, see #17 ) to keep and history.

I've setup a milestone for that: https://github.com/mozilla-b2g/B2GOS-community/milestones/Adapt%20the%20documentation%20to%20the%20new%20phase
The goal is to do it before next meeting.

**Comment by lapineige** [comment]
@kskarthik would you like to help me on this point ?

**Comment by lapineige** [comment]
Can be done on Thursday #19

**Comment by kskarthik** [comment]
I'm ready. I fixed transition links on landing page

**Comment by lapineige** [comment]
- [x] After changing wiki links (from /B2G/Transition_Project) in #17, update links on MDN

Found links to change only here: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS (to be confirmed)
