### ISSUE TITLE
Do a documentation working session on Thursday 2

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#19]
(decided during today documentation meeting)

Goal: have a working session to work on documentation task together, while discussing via chat/etherpad/vidyo to coordinate our efforts.

It's planned on Thursday 2, between 17:00-19:00 CEST > so 3 to 5 pm UTC

**Comment by kskarthik** [comment]
i will remove the transition branch info soon on mdn

**Comment by kskarthik** [comment]
i mean after kanikani merges into master.

**Comment by ensowhat** [comment]
https://discourse.mozilla-community.org/t/documentation-working-session-on-thursday-2016-06-02/8989
