### ISSUE TITLE
Draft an agenda for the provisionnal council

### ISSUE THREAD

**Issue by ensowhat** [mozilla-b2g/B2GOS-community#2]
- [x] Define the council goal, power, composition
- [x] Make an agenda for council tasks, creation, and next governance steps
- [ ] ask on dev-fxos mailing-list if people want to join
- [ ] Finalize the council team

**Comment by lapineige** [comment]
Meeting to define this https://discourse.mozilla-community.org/t/provisional-council-creation/8867

**Comment by lapineige** [comment]
Meeting report: https://public.etherpad-mozilla.org/p/B2G_gov_model_proposal

TODO: ask on the mailing-list if people want to volunteer
