### ISSUE TITLE
Translate main wiki page

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#20]
- [ ] Create the main wiki page, update it with new status #17 
- [ ] Call for translation on the main wiki page https://wiki.mozilla.org/B2G/
- [ ] Contact previous translators

**Comment by kuramaluka** [comment]
Italian translation is, more or less, in progress.

Unfortunately there was a little problem with the renaming of the url of the page (whom still refered to Firefox OS) ... and now everything is blocked due to a bug. 

If you want to know more:
https://bugzilla.mozilla.org/show_bug.cgi?id=1279908

**Comment by Ryuno-Ki** [comment]
I couldn't find documentation about translation (here on GitHub). Is there a need for a German one?

**Comment by kuramaluka** [comment]
Ryuno-Ki, just look at the MDN pages of [B2GOS](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS) :)

From what I can see the deutsch translation is outdated: [https://developer.mozilla.org/de/Firefox_OS]. It still has the structure of Firefox os :) So, if you want, you can start to translate it :+1:

**Comment by Ryuno-Ki** [comment]
What about links in there? Especially to wiki.mozilla.org

**Comment by kuramaluka** [comment]
I made a little mess, this is the wiki page topic, not the MDN one, sorry Ryuno-Ki!

Anyway, I think we need a translation for both of them ([wiki](https://wiki.mozilla.org/B2G) and [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS)).

Just delete the previous content, copy the new (english) one and translate it. We've a back-up copy of all the previuos documentantion and we're going to reuse it when needed. :)

**Comment by Ryuno-Ki** [comment]
@kuramaluka I've translated the German Firefox OS page on MDN :-)

There's just a `zone-callout` around the image + hint I cannot get rid of O_o

> Anyway, I think we need a translation for both of them (wiki and MDN).

I'm for clarifying this by editing this repo's README.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills Can you tell, whether wiki.mozilla.org offers translation at all?

From what I can see it's a MediaWiki - Wikipedia has translations in the left hand pane. Another way was used at [my distro's wiki](https://wiki.sabayon.org/index.php?title=En:Main_Page) - so what would need to be done from Mozilla if we would want to have translation for community pages like B2G OS?

**Comment by chrisdavidmills** [comment]
hi there,

Sorry for being so late to answer this — I completely missed it. I'm afraid I don't know anything about translations for wiki.mozilla.org. I will talk to a few people to see if I can figure anything out.

**Comment by imyaman** [comment]
What URL would be ok for Korean translation? Would https://wiki.mozilla.org/ko/B2G be ok?
Thank you.

**Comment by lapineige** [comment]
Thanks @chrisdavidmills , I'm looking forward for your information :smiley:
