### ISSUE TITLE
Review the Call for Contribution - Spanish translation

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#21]
The Spanish translation of the Call for Contribution need some review: https://discourse.mozilla-community.org/t/call-for-contributors-final-version-update-we-need-translations/8601/37
- [x] Review the Spanish translation
- [x] Put it on the wiki https://wiki.mozilla.org/B2G/Transition_Project/Call_For_Contribution
- [x] Add translators/reviewers contact info on the wiki #5

**Comment by lapineige** [comment]
Seems like the final version is here: https://discourse.mozilla-community.org/t/call-for-contributors-final-version-update-we-need-translations/8601/47
(But another review is always appreciated :wink:)

Translator info is on the wiki (but only for italian)

**Comment by lapineige** [comment]
Up ! :)

**Comment by lapineige** [comment]
Up !

**Comment by xerz-one** [comment]
Done! The final version is available at Etherpad: https://etherpad.wikimedia.org/p/B2G_traducion_espanol

**Comment by lapineige** [comment]
Closed.
Solved in this discourse post: https://discourse.mozilla-community.org/t/call-for-contributors-final-version-update-we-need-translations/8601/66
Thanks to all the translators / reviewers ! :)
