### ISSUE TITLE
Remove translation from MDN main page [edit] we need to add a macro, removal is not possible

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#22]
Old translation of https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS are still here (as a legacy of Firefox OS period).
They are no longer relevant - and not really useful for future translation.
They should be removed\* to avoid confusing people - if their read translation, they don't see the (updated) English page.
- [x] \* Update: translation can't be removed, we should add a macro at the top of the page
  `{{ObsoleteTranslation("https://lists.mozilla.org/listinfo/dev-fxos","the dev-fxos mailing list")}}`

**Comment by lapineige** [comment]
Anyone know how to remove all those pages ? (if possible in a single shot, they are quite numerous...)

**Comment by Ryuno-Ki** [comment]
I'll ask Chris Mills.

**Comment by Ryuno-Ki** [comment]
Feedback from Chris:

> Normal pages can only be deleted by admins.
> Translations can’t be deleted at all, which is a bit of a shortcoming of the MDN site. To help with this, I made the following macro:
> `{{ObsoleteTranslation("https://lists.mozilla.org/listinfo/dev-fxos","the dev-fxos mailing list")}}`
> you can see it in action in https://developer.mozilla.org/fr/Firefox_OS

So the answer is, translations cannot be removed.

**Comment by lapineige** [comment]
Thanks @Ryuno-Ki :smiley:
That's an important thing to keep in mind, we can't remove pages easily.

So let's use this macro on every translated pages. (main task edited)

**Comment by imyaman** [comment]
chrisdavidmills changed /Mozilla/Firefox_OS to /Mozilla/B2G_OS at  May 4, 2016, 5:00:02 PM.
Can he also change /ko/docs/Mozilla/Firefox_OS to /ko/docs/Mozilla/B2G_OS?

**Comment by lapineige** [comment]
I guess it's possible.
We should ask it, but I suppose it's a manual change.
It's better to do it for all translation, rather than contacting him every time we have a new translation (and there is a **lot** of translations).
But I a imagine it's a manual process for all the translation, let's wait for a couple of them to be ready, let's say 5 of them

**Comment by kskarthik** [comment]
@lapineige this issue is resolved

**Comment by lapineige** [comment]
Oh you're right thx :)
