### ISSUE TITLE
Translate main MDN page

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#23]
https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS need to be translated

And if we don't have people to do it, we should add this macro on the old translations #22 (as we can't remove it)

Ongoing translations:
- [x] Italian (made by Luca and Enrico)
- [x] German version completed
  /!\ Need review
- [x] French version completed (made by xdelatour and [?])
- [x] Korean version completed
- [ ] Spanish
- [ ] Japanese
- [ ] Hindi
- [ ] Swedish
  ...

**Comment by gaby2300** [comment]
I'm really sorry I won't be able to help with Spanish! I broke an elbow and
have to be operated. There's not much I can do with one hand so....
Best regards,
Gabriela

**Comment by lapineige** [comment]
No worries (everyone help how s-he can), and good recovery ;)

**Comment by gaby2300** [comment]
Many thanks! I'll post again as soon as I recover my use of both hands

**Comment by Ryuno-Ki** [comment]
Count me in for German translation :-)

**Comment by ghost** [comment]
And me in the Spanish one! XD

**Comment by lapineige** [comment]
Good news :)
Just give an update when it's ready, when it need review ;)

**Comment by Ryuno-Ki** [comment]
I updated the German one at https://developer.mozilla.org/de/Firefox_OS.

**Comment by lapineige** [comment]
Is it a final version ?

**Comment by Ryuno-Ki** [comment]
From my PoV, yes. I covered the whole English original (and even reported the wrong Discourse link on Telegram :-)).

I don't know, whether another German speaking Mozillian wants to review it.

**Comment by ghost** [comment]
Spanish is done! it's just that there is no navigation bar at the left and the Firefox OS phone is still there, but the translation is done, if you need to translate any other documents to Spanish I'm in. :D
https://developer.mozilla.org/es/Firefox_OS

**Comment by Ryuno-Ki** [comment]
@edangor I discovered, that translators are "collected" at https://wiki.mozilla.org/B2G/Transition_Project/Working_Groups#Translation - do you have an account there?

If not, I can add you if you want.

**Comment by Ryuno-Ki** [comment]
@edangor wrote

> it's just that there is no navigation bar at the left

@lapineige I wonder, whether it was created by `{{firefoxOSSidebar}}` and/or it is affected by `id="Subnav"` which I got rid off of https://developer.mozilla.org/de/docs/Mozilla/Firefox_OS$compare?locale=de&to=1071506&from=821659

**Comment by ghost** [comment]
@Ryuno-Ki 

> do you have an account there?
> 
> If not, I can add you if you want.

No, I don't have an account could you add me please?

**Comment by Ryuno-Ki** [comment]
@edangor Done.

**Comment by imyaman** [comment]
Korean version is completed.
https://github.com/imyaman/MDN_Korean/blob/gh-pages/Mozilla/B2G_OS.html <- source
http://imyaman.github.io.youre.space/MDN_Korean/Mozilla/B2G_OS.html <- preview

**Comment by imyaman** [comment]
The URL of Korean page is /ko/docs/Mozilla/Firefox_OS, not /ko/docs/Mozilla/B2G_OS.
How can I change the URL? Thank you.

**Comment by lapineige** [comment]
> Korean version is completed.
> :-o That's great, thank you !

You can add it on MDN ;)

> The URL of Korean page is /ko/docs/Mozilla/Firefox_OS, not /ko/docs/Mozilla/B2G_OS.
> How can I change the URL?

Good question, I don't know. We should ask Chris Mills.
It might be related to #22

**Comment by imyaman** [comment]
The macro just adds a warning like 

```
Important: This translation is out-of-date, and needs to be updated to reflect the current content of the English version. If you want to contribute or ask questions, contact us at B2G OS.
```

You can see the warning here https://developer.mozilla.org/ko/docs/Mozilla/Firefox_OS

I think there must be a new page if it is impossible to remove redirection.

**Comment by lapineige** [comment]
I mean it might be the same limitation, only admin can do it.
Let's translate some pages, we will ask Chris to do it for all of them at the same time.

**Comment by kuramaluka** [comment]
The italian version is still blocked due to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1279908

**Comment by kuramaluka** [comment]
The italian translation is now complete :) https://developer.mozilla.org/it/docs/Mozilla/B2G_OS

**Comment by lapineige** [comment]
Great ! :)
I've added a couple of languages, based on the list of people in the translation working group https://wiki.mozilla.org/B2G/Transition_Project/Working_Groups

**Comment by lapineige** [comment]
Please everyone translation this page (or any MDN page): subscribe to it to be updated of the changes ;)

**Comment by Ryuno-Ki** [comment]
@lapineige Stupid question but may you explain how to subscribe to a MDN page? Only the version I translated or is it worthwhile to subscribe to English version as well?

What is the current state of French translation?

What about the missing ones (Spanish, Japanese, Hindi, Swedish)?

**Comment by imyaman** [comment]
Korean version is updated.

**Comment by kuramaluka** [comment]
If you want to be updated (particularly for translations) with the work we are all doing on MDN, just **Subscribe to the landing page and the all sub articles**:

![schermata del 2016-08-08 20-34-25](https://cloud.githubusercontent.com/assets/11256504/17491346/89859abe-5da7-11e6-853d-80f161ada3ab.png)

**Comment by lapineige** [comment]
@Ryuno-Ki There's no stupid question ;)
Look at the screenshot shared above (thx @kuramaluka).
Yes subscribe to the English version, to know when to update translations.
(and also, if you make change, please add a title - it's faster to know what changed ;) )

I didn't have any time to work on the French version. _edit_: I just checked: someone did it, thanks :)

@imyaman  cool thx :)

**Comment by amitkumarj441** [comment]
Hey @lapineige , 

Count me in for Hindi translation and can review too!
Please let me know how to start with translation and where!

Cheers,
Amit Kumar Jaiswal

**Comment by lapineige** [comment]
You're welcome :)

Basically, go to this page: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS
Click on Languages (up right), select the one you wanna edit, log in -using github account) and edit the page (button up right).

**Comment by marsf** [comment]
Japanese page is updated to the latest en-US revision. ;-)

**Comment by lapineige** [comment]
Reminder: you can follow the status of the doc translation here: https://developer.mozilla.org/en-US/docs/MDN/Doc_status/B2G_OS
(on the localization part, you can click on your language to see it)
