### ISSUE TITLE
B2G installer is signed - let's update the documentation !

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#26]
B2G Installer has been signed ! :)
https://discourse.mozilla-community.org/t/b2g-installer-add-on-for-firefox/7523/17

So let's update [the documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Building_and_installing_Firefox_OS/B2G_installer_add-on#Installation), it's a lot easier to install it now.
- [x] Update the installation doc
- [ ] Enhance B2G installer add-on description

**Comment by lapineige** [comment]
Wow already done by @TitanNano ! :)

**Comment by kuramaluka** [comment]
We should also change the "Firefox OS Installer" main png into a "B2G OS Installer" png!

**Comment by kskarthik** [comment]
@kuramaluka i made a PR already https://github.com/mozilla-b2g/b2g-installer/pull/50
