### ISSUE TITLE
Update "Preparing your first B2G build" with info about mozilla-central builds

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#29]
Currently this page: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Preparing_for_your_first_B2G_build
Only talk about building with pine and kanikani branches.

We need to update it to explain what these branches are, how to build with mozilla-central (explaining that using pine/kanikani is an extra option)

**Comment by kskarthik** [comment]
@lapineige I fixed it https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Preparing_for_your_first_B2G_build 

bug fixed: https://github.com/mozilla-b2g/b2g-manifest/commit/496bb6092e73d997edc9045ef837e40e5f9ee543

**Comment by lapineige** [comment]
Shouldn't we keep some info about using kanikani/pine ? (in case we keep them in the future ?)

**Comment by kskarthik** [comment]
i think no need
