### ISSUE TITLE
Italian translation log

### ISSUE THREAD

**Issue by kuramaluka** [mozilla-b2g/B2GOS-community#30]
This, just to keep community and translators up to date with the work we're currently doing on MDN.

MDN is already huge in terms of pages and subarticles, so it's necessary to make a register as much as possible complete.

**Note**: remember to keep pages' english names.

Translated:
- [x] [Landing page](https://developer.mozilla.org/it/docs/Mozilla/B2G_OS);
- [x] [Build and install overview](https://developer.mozilla.org/it/docs/Mozilla/B2G_OS/Building_and_installing_Firefox_OS);
- [x] [Localizing B2G OS](https://developer.mozilla.org/it/docs/Mozilla/B2G_OS/Developing_Firefox_OS/Localizing_Firefox_OS)
- [x] Sidebar ( please refer to this [discourse topic](https://discourse.mozilla-community.org/t/sidebar-translation/10190).

Now working on:
- [ ] [B2G OS build process summary](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Building_and_installing_B2G_OS/B2G_OS_build_process_summary)

To do:
- All the remainings.

**Comment by lapineige** [comment]
Looks like it's finished. I close this task.
Thanks again for this work :)

**Comment by kuramaluka** [comment]
Lapi, could you please reopen the task? :) If possible, I would like to use use it, tracking overall the translation process. Just imagine in "to do list" there are all the other untranslated pages :D

**Comment by lapineige** [comment]
Yes sure :)
