### ISSUE TITLE
Architecture page linked on Main is still not ported.

### ISSUE THREAD

**Issue by novski** [mozilla-b2g/B2GOS-community#31]
We have to update this page:
https://developer.mozilla.org/en-US/docs/Archive/Firefox_OS/Platform/Architecture

**Comment by lapineige** [comment]
I think @kskarthik is working on that topic, with this page on MDN: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/B2G_OS_Architecture

The content is still basic, feel free to help :)

**Comment by novski** [comment]
Ok. True. I have seen that. The old page is much larger. Do we discuss the content of that page here or in discourse?

**Comment by lapineige** [comment]
> Do we discuss the content of that page here or in discourse?

Discourse is more followed, with more technical people.
I'd say that the discussions on content should be done on discourse, and here we just keep track of what need to be done / is done.

**Comment by kskarthik** [comment]
We could reuse some content from the old architecture page :)  I filed a bug & set a topic on discourse also https://discourse.mozilla-community.org/t/b2g-os-architecture-page/10787

**Comment by lapineige** [comment]
Yes, after checking it's still relevant. (which I guess it will be for the gonk layer, for instance)
