### ISSUE TITLE
Identify translators 

### ISSUE THREAD

**Issue by ensowhat** [mozilla-b2g/B2GOS-community#5]
… and efficient ways to contact them.
Cf. https://wiki.mozilla.org/B2G/Transition_Project/Call_For_Contribution
- [x] Page for working groups created on the wiki #1  https://wiki.mozilla.org/B2G/Transition_Project/Working_Groups
- [x] Call for people on discourse to add information on the page
- [ ]  People added their contact info

**Comment by lapineige** [comment]
The whole list for the call for contribution should be there: https://discourse.mozilla-community.org/t/call-for-contributors-draft-that-need-review-and-help-for-writing/8601

**Comment by lapineige** [comment]
Page for working groups created (see https://github.com/ensowhat/B2GOS-community/issues/1), we should ask people to add their infos on this page.

**Comment by ensowhat** [comment]
Add the French community ML link, as they're willing to help on translation.

**Comment by ensowhat** [comment]
- [ ] Ping people who already translated something. :)

**Comment by gaby2300** [comment]
Hello!
I could help with the Spanish translation. I would need to know where I can find whatever I have to translate.

**Comment by lapineige** [comment]
Hi @gaby2300 
Please add you name on the wiki page ;)
You can check that too, I think they need some review: https://discourse.mozilla-community.org/t/call-for-contributors-final-version-update-we-need-translations/8601/37

**Comment by gaby2300** [comment]
Hi, many thanks for answering me so quickly!

I can add my name to the wiki but is seems @erotavlas has already
translated:

https://wiki.mozilla.org/B2G/Transition_Project/Call_For_Contribution into
Spanish, not on the wiki but in an etherpad. Maybe it would better is he
adds himself to the wiki first?

BTW, the translation ends with the following links:
1. _https://wiki.mozilla.org/Booting_to_the_Web_
   https://wiki.mozilla.org/Booting_to_the_Web
   2.
   _https://blog.mozilla.org/blog/2015/12/09/firefox-os-pivot-to-connected-devices/_
   https://blog.mozilla.org/blog/2015/12/09/firefox-os-pivot-to-connected-devices/
2. _https://wiki.mozilla.org/Connected_Devices_
   https://wiki.mozilla.org/Connected_Devices
3. _https://wiki.mozilla.org/B2G/Transition_Project_
   https://wiki.mozilla.org/B2G/Transition_Project
4. _https://discourse.mozilla-community.org/c/firefox-os-participation_
   https://discourse.mozilla-community.org/c/firefox-os-participation
5. _https://wiki.mozilla.org/IRC_ https://wiki.mozilla.org/IRC
6. _https://telegram.me/B2GOS_ https://telegram.me/B2GOS
7. _https://wiki.mozilla.org/B2G/Meeting_
   https://wiki.mozilla.org/B2G/Meeting
8. _https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS_
   https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS

Do these also need to be translated? If so, I could start to do it and also
ask Mozilla Hispano's localization team if someone wants to help too.

Many thanks!
Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

http://www.mozilla-hispano.org
http://twitter.com/mozilla_hispano
http://facebook.com/mozillahispano

**Comment by lapineige** [comment]
>  I can add my name to the wiki but is seems @erotavlas has already translated:

Sorry, I mean on this page: https://wiki.mozilla.org/B2G/Transition_Project/Working_Groups
(first post edited)

> Do these also need to be translated? If so, I could start to do it and also ask Mozilla Hispano's localization team if someone wants to help too.

Right now, they will change too much. So I think it's too soon.
Also we want to identify translator and how to contact them for this purpose. When we will need a translation, contacting people will be easy.
Also you can subscribe to the the Translation label on this github repo.

**Comment by gaby2300** [comment]
I added myself to the wiki you mentioned and also subscribed to the Translation label here.
Many thanks lapineige!

**Comment by lapineige** [comment]
Many thanks to you ! ;)

**Comment by lapineige** [comment]
So as a kind of synthesis, we now have 2 translators for French/Italian/Spanish.

TODO:
- [ ] Contact the Japanese/Chinese/Korean/German translator of the call for contribution.
- [ ] Contact the other French translators
- [ ] Contact the other Italian translator (if I'm right, we miss one of them)

**Comment by lapineige** [comment]
I will post a quick reminder on discourse, if after that we still need more people we could send them a private message.

**Comment by lapineige** [comment]
TODO: need to identify Korean, Chinese, German translators

**Comment by Ryuno-Ki** [comment]
Added myself for German translators.

**Comment by imyaman** [comment]
I am the Korean translator.

**Comment by lapineige** [comment]
:+1: Great, only remaining the Chinese translator now.

And thanks for adding you in the wiki ! :smiley:

**Comment by imyaman** [comment]
No problem. ;-)

**Comment by lapineige** [comment]
TODO: contact Chinese translator + Hindi + Persian
