### ISSUE TITLE
Reformulate "Compatible Devices" page on MDN

### ISSUE THREAD

**Issue by lapineige** [mozilla-b2g/B2GOS-community#8]
A rewrite of this page is needed to adapt to the current state: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Building_and_installing_B2G_OS/Compatible_Devices
- [x] Change Firefox OS > B2G OS
- [x] Add the current build/support status for the phones
- [x] Change the list of fxos-supported devices to inform that a port is possible - but need contributors help.
- [x] Move the legacy devices to highlight that there are no longer supporter
- [x] Review the technical content
- [x] Review the shape or the page
- [x] Delete https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Supported_Devices and change the link in https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS

**Comment by lapineige** [comment]
Should we archive the page, and reuse the content here ? https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Supported_Devices

**Comment by kskarthik** [comment]
@lapineige You can check all the boxes. I fixed those & regarding that Suuported_Devices page... Hmm... better we kill that ?

**Comment by lapineige** [comment]
Well, it's better now, but still unclear IMHO.
We need to clearly separate the categories, between developer phones, community maintained phones, ongoing work, potential devices (supported by Fxos 2.6, but still without any builds) and legacy devices.
We could also is this page to replace this one: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Supported_Devices

**Comment by lapineige** [comment]
I changed the page, please review it to confirm is more clear now.
The information about build status, B2G Installer information or devices base android version has to be confirmed.

Todo-list updated

**Comment by lapineige** [comment]
Idea to improve this content #13
This is not a priority, as we still have few devices / features and information on discourse topic.

---

@ensowhat could you take a look at the shape of the page, to be sure it's clear ?

**Comment by lapineige** [comment]
> Delete https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Supported_Devices and change the link in https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS
> Done during the working session #19 

The page still need to refinement and revision

**Comment by lapineige** [comment]
- [ ]  check Z3 status

**Comment by lapineige** [comment]
Closed. Need some check for Z3 status, and some addition (like #27  #28) but the main rewrap/review is done.
